# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(880, 600)
        MainWindow.setStyleSheet("background-image: url(:/background/signin.png);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(390, 370, 101, 41))
        self.submitButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 255);\n"
"border-radius:4px;")
        self.submitButton.setObjectName("submitButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(600, 120, 181, 211))
        self.verticalLayoutWidget.setStyleSheet("color: rgb(255, 255, 255);")
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mondayBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.mondayBox.setStyleSheet("color: rgb(131, 131, 131);")
        self.mondayBox.setObjectName("mondayBox")
        self.verticalLayout.addWidget(self.mondayBox)
        self.tuesdayBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.tuesdayBox.setStyleSheet("color: rgb(131, 131, 131);")
        self.tuesdayBox.setObjectName("tuesdayBox")
        self.verticalLayout.addWidget(self.tuesdayBox)
        self.wednesdayBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.wednesdayBox.setStyleSheet("color: rgb(131, 131, 131);")
        self.wednesdayBox.setObjectName("wednesdayBox")
        self.verticalLayout.addWidget(self.wednesdayBox)
        self.thursdayBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.thursdayBox.setStyleSheet("color: rgb(131, 131, 131);")
        self.thursdayBox.setObjectName("thursdayBox")
        self.verticalLayout.addWidget(self.thursdayBox)
        self.fridayBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.fridayBox.setStyleSheet("color: rgb(131, 131, 131);")
        self.fridayBox.setObjectName("fridayBox")
        self.verticalLayout.addWidget(self.fridayBox)
        self.saturdayBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.saturdayBox.setStyleSheet("color: rgb(131, 131, 131);")
        self.saturdayBox.setObjectName("saturdayBox")
        self.verticalLayout.addWidget(self.saturdayBox)
        self.sundayBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.sundayBox.setStyleSheet("color: rgb(131, 131, 131);")
        self.sundayBox.setObjectName("sundayBox")
        self.verticalLayout.addWidget(self.sundayBox)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(290, 120, 251, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.timeLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.timeLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:4px;\n"
"border:2px solid gray;")
        self.timeLineEdit.setObjectName("timeLineEdit")
        self.gridLayout.addWidget(self.timeLineEdit, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setStyleSheet("color: rgb(131, 131, 131);")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setStyleSheet("color: rgb(131, 131, 131);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.activityLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.activityLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:4px;\n"
"border:2px solid gray;")
        self.activityLineEdit.setObjectName("activityLineEdit")
        self.gridLayout.addWidget(self.activityLineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setStyleSheet("color: rgb(131, 131, 131);")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.descriptionLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.descriptionLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:4px;\n"
"border:2px solid gray;")
        self.descriptionLineEdit.setObjectName("descriptionLineEdit")
        self.gridLayout.addWidget(self.descriptionLineEdit, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 880, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.submitButton.setText(_translate("MainWindow", "Submit"))
        self.mondayBox.setText(_translate("MainWindow", "Monday"))
        self.tuesdayBox.setText(_translate("MainWindow", "Tuesday"))
        self.wednesdayBox.setText(_translate("MainWindow", "Wednesday"))
        self.thursdayBox.setText(_translate("MainWindow", "Thursday"))
        self.fridayBox.setText(_translate("MainWindow", "Friday"))
        self.saturdayBox.setText(_translate("MainWindow", "Saturday"))
        self.sundayBox.setText(_translate("MainWindow", "Sunday"))
        self.label_3.setText(_translate("MainWindow", "Time"))
        self.label.setText(_translate("MainWindow", "Activity"))
        self.label_2.setText(_translate("MainWindow", "Description"))
import anothertest


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
